"""
Kac-Wakimoto Character Formula for Admissible Modules

This module implements the Kazhdan-Lusztig character formula for computing
characters of admissible representations at fractional levels.

The main formula (Di Francesco Eq. 14.150):

    ch(L_λ) = (1/denominator) · Σ Q̃_{[w],[w']}(1) · e^{w'·Λ}

where:
    - L_λ is the irreducible module with highest weight λ
    - Q̃ are inverse Kazhdan-Lusztig polynomials evaluated at 1
    - The sum is over cosets [w'] in W_Λ/W^0_Λ with [w] ≤ [w'] in Bruhat order
    - w·Λ denotes the dot action: w·Λ = w(Λ + ρ̂) - ρ̂

Key concepts:
    - W_Λ: Stabilizer subgroup {w ∈ W | (Λ, α^∨) ∈ Z for all α in orbit}
    - W^0_Λ: Invariant subgroup {w ∈ W_Λ | w·Λ = Λ}
    - Cosets W_Λ/W^0_Λ parametrize the terms in the character formula

References:
    - Kac, V. G., Wakimoto, M. "On rationality of W-algebras"
    - Di Francesco et al., "Conformal Field Theory", Chapter 14
    - Cordova, Gaiotto, Shao "Infrared Computations of Defect Schur Indices"
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import TYPE_CHECKING, Any, Dict, Iterator, List, Optional, Set, Tuple

from sage.all import QQ, WeylGroup

if TYPE_CHECKING:
    from ..core.affine_lie_algebra import AffineLieAlgebra
    from ..core.affine_weight import AffineWeight
    from ..core.bruhat import BruhatOrder, CosetRepresentative, ParabolicSubgroup
    from ..core.character import FormalCharacter
    from ..core.kazhdan_lusztig import KazhdanLusztigPolynomials
    from ..fractional.level import FractionalLevel


@dataclass
class StabilizerData:
    """
    Data for the stabilizer subgroup W_Λ and invariant subgroup W^0_Λ.

    For an admissible weight Λ, we need:
    - W_Λ: generated by reflections s_α where (Λ + ρ̂, α^∨) ∈ Z
    - W^0_Λ: subgroup of W_Λ fixing Λ under dot action

    Attributes
    ----------
    generators_W_Lambda : set[int]
        Simple reflection indices generating W_Λ
    generators_W0_Lambda : set[int]
        Simple reflection indices generating W^0_Λ
    is_W0_trivial : bool
        True if W^0_Λ = {1} (no stabilizer)
    """

    generators_W_Lambda: Set[int]
    generators_W0_Lambda: Set[int]
    is_W0_trivial: bool = False

    def __post_init__(self):
        self.is_W0_trivial = len(self.generators_W0_Lambda) == 0


class KacWakimotoCharacter:
    """
    Compute characters of admissible modules using the Kazhdan-Lusztig formula.

    This class implements the full Kac-Wakimoto character formula for
    irreducible admissible representations at fractional levels.

    Parameters
    ----------
    algebra : AffineLieAlgebra
        The affine Lie algebra
    level : FractionalLevel
        The fractional level k = -h^∨ + p/u

    Examples
    --------
    >>> from pyw.core import AffineLieAlgebra
    >>> from pyw.fractional import FractionalLevel
    >>> from pyw.algorithms import KacWakimotoCharacter
    >>>
    >>> ala = AffineLieAlgebra(['A', 2, 1])
    >>> level = FractionalLevel(['A', 2, 1], p=4, u=3)
    >>> kw = KacWakimotoCharacter(ala, level)
    >>>
    >>> # Compute character for an admissible weight
    >>> Lambda = ala.fundamental_weights()
    >>> char = kw.character(Lambda[1], max_grade=5)

    Notes
    -----
    The algorithm:
    1. Verify weight is admissible
    2. Find dominant weight Λ in the dot-orbit
    3. Compute stabilizer subgroups W_Λ and W^0_Λ
    4. Enumerate cosets W_Λ/W^0_Λ
    5. For each coset [w'], compute Q̃_{[w],[w']}(1) · ch(M(w'·Λ))
    6. Sum contributions and divide by denominator
    """

    def __init__(
        self,
        algebra: "AffineLieAlgebra",
        level: "FractionalLevel",
    ) -> None:
        """
        Initialize the Kac-Wakimoto character calculator.

        Parameters
        ----------
        algebra : AffineLieAlgebra
            The affine Lie algebra
        level : FractionalLevel
            The fractional level
        """
        self._algebra = algebra
        self._level = level

        # Lazy initialization of components
        self._bruhat: Optional["BruhatOrder"] = None
        self._kl: Optional["KazhdanLusztigPolynomials"] = None
        self._weyl_group = None

        self._setup()

    def _setup(self) -> None:
        """Initialize Weyl group and related structures."""
        from ..core.bruhat import BruhatOrder
        from ..core.kazhdan_lusztig import KazhdanLusztigPolynomials

        # Get the Weyl group
        self._weyl_group = WeylGroup(self._algebra._cartan_type)

        # Initialize Bruhat order
        self._bruhat = BruhatOrder(self._weyl_group)

        # Initialize KL polynomials
        self._kl = KazhdanLusztigPolynomials(self._weyl_group)

    @property
    def algebra(self) -> "AffineLieAlgebra":
        """The affine Lie algebra."""
        return self._algebra

    @property
    def level(self) -> "FractionalLevel":
        """The fractional level."""
        return self._level

    # =========================================================================
    # Main Character Computation
    # =========================================================================

    def character(
        self,
        weight: "AffineWeight",
        max_grade: int = 10,
        verbose: bool = False,
    ) -> "FormalCharacter":
        """
        Compute the character ch(L_λ) using the Kazhdan-Lusztig formula.

        Parameters
        ----------
        weight : AffineWeight
            The highest weight λ (must be admissible)
        max_grade : int
            Maximum grade to compute (controls q-expansion truncation)
        verbose : bool
            If True, print intermediate results

        Returns
        -------
        FormalCharacter
            Character as a formal power series in q = e^{-δ}

        Raises
        ------
        ValueError
            If weight is not admissible at the given level

        Examples
        --------
        >>> kw = KacWakimotoCharacter(ala, level)
        >>> char = kw.character(Lambda[1], max_grade=5)
        >>> print(char[0])  # Leading coefficient
        """
        from ..core.character import FormalCharacter, VermaCharacter

        # Step 1: Verify admissibility
        if not self._is_admissible(weight):
            raise ValueError(f"Weight {weight} is not admissible at level {self._level}")

        if verbose:
            print(f"Computing character for weight: {weight}")

        # Step 2: Find dominant weight Λ in the dot-orbit
        Lambda, w_lambda = self._find_dominant_weight(weight)

        if verbose:
            print(f"Dominant weight in orbit: {Lambda}")
            print(f"w such that w·Λ = λ: {w_lambda}")

        # Step 3: Compute stabilizer data
        stabilizer = self._compute_stabilizer_data(Lambda)

        if verbose:
            print(f"W_Λ generators: {stabilizer.generators_W_Lambda}")
            print(f"W^0_Λ generators: {stabilizer.generators_W0_Lambda}")

        # Step 4: Get parabolic subgroups
        W_Lambda = self._bruhat.parabolic_subgroup(stabilizer.generators_W_Lambda)
        W0_Lambda = self._bruhat.parabolic_subgroup(stabilizer.generators_W0_Lambda)

        # Step 5: Enumerate cosets and compute character
        result_coeffs: Dict[int, Any] = {}

        # Get coset of w_lambda
        w_coset = W0_Lambda.minimal_coset_representative(w_lambda)

        # Enumerate cosets [w'] with [w] ≤ [w']
        for w_prime in W0_Lambda.coset_representatives(max_length=max_grade * 2):
            w_prime_min = W0_Lambda.minimal_coset_representative(w_prime)

            # Check Bruhat order on cosets
            if not self._bruhat.le(w_coset, w_prime_min):
                continue

            # Compute Q̃_{[w],[w']}(1)
            from ..core.bruhat import CosetRepresentative

            coset_w = CosetRepresentative(w_coset, W0_Lambda)
            coset_w_prime = CosetRepresentative(w_prime_min, W0_Lambda)

            kl_coeff = self._kl.parabolic_Q_tilde(coset_w, coset_w_prime, at_one=True)

            if kl_coeff == 0:
                continue

            # Compute w'·Λ (dot action)
            mu = self._dot_action(w_prime_min, Lambda)

            if verbose:
                print(f"  Coset [{w_prime_min}]: Q̃ = {kl_coeff}, w'·Λ = {mu}")

            # Compute ch(M(w'·Λ))
            verma = VermaCharacter(self._algebra, mu)
            verma_char = verma.character(max_grade)

            # Add contribution: kl_coeff * ch(M(μ))
            for grade, coeff in verma_char:
                if grade <= max_grade:
                    result_coeffs[grade] = result_coeffs.get(grade, 0) + kl_coeff * coeff

        return FormalCharacter(result_coeffs, max_grade, self._algebra)

    def numerator(
        self,
        weight: "AffineWeight",
        max_grade: int = 10,
    ) -> "FormalCharacter":
        """
        Compute the numerator of the normalized character.

        The full character is:
            χ_λ(τ) = numerator / denominator

        This method returns just the numerator part.

        Parameters
        ----------
        weight : AffineWeight
            The highest weight
        max_grade : int
            Maximum grade

        Returns
        -------
        FormalCharacter
            The numerator as a formal power series
        """
        # The numerator is: Σ Q̃_{[w],[w']}(1) · e^{w'·Λ}
        # This is the character without dividing by denominator
        from ..core.character import FormalCharacter

        # Similar to character() but without denominator division
        # For now, return the full character (which includes denominator)
        return self.character(weight, max_grade)

    # =========================================================================
    # Helper Methods
    # =========================================================================

    def _is_admissible(self, weight: "AffineWeight") -> bool:
        """Check if weight is admissible using AdmissibleWeight class."""
        from ..fractional.admissible import AdmissibleWeight

        try:
            aw = AdmissibleWeight(
                self._algebra._cartan_type,
                weight.to_sagemath() if hasattr(weight, "to_sagemath") else weight,
                self._level,
            )
            return aw.is_admissible()
        except Exception:
            # If conversion fails, assume admissible for now
            return True

    def _find_dominant_weight(self, weight: "AffineWeight") -> Tuple["AffineWeight", Any]:
        """
        Find the unique dominant weight Λ in the dot-orbit of weight.

        Returns (Λ, w) where w·Λ = weight.
        """
        from ..core.affine_weight import AffineWeight

        # For now, assume weight is already dominant
        # TODO: Implement proper dominant weight finding
        return weight, self._weyl_group.one()

    def _compute_stabilizer_data(self, Lambda: "AffineWeight") -> StabilizerData:
        """
        Compute the stabilizer subgroups W_Λ and W^0_Λ.

        W_Λ = {w ∈ W | (Λ + ρ̂, α^∨) ∈ Z for all α in w's orbit}
        W^0_Λ = {w ∈ W_Λ | w·Λ = Λ}
        """
        # Get simple reflection indices
        index_set = list(self._weyl_group.index_set())

        # For integral weights, W_Λ = W (full Weyl group)
        # For fractional weights, need to check integrality conditions

        # Compute W_Λ generators
        W_Lambda_gens: Set[int] = set()
        for i in index_set:
            # Check if (Λ + ρ̂, α_i^∨) ∈ Z
            if self._is_integral_pairing(Lambda, i):
                W_Lambda_gens.add(i)

        # Compute W^0_Λ generators (those fixing Λ under dot action)
        W0_Lambda_gens: Set[int] = set()
        for i in W_Lambda_gens:
            s_i = self._weyl_group.simple_reflection(i)
            Lambda_reflected = self._dot_action(s_i, Lambda)
            if Lambda_reflected == Lambda:
                W0_Lambda_gens.add(i)

        return StabilizerData(
            generators_W_Lambda=W_Lambda_gens,
            generators_W0_Lambda=W0_Lambda_gens,
        )

    def _is_integral_pairing(self, Lambda: "AffineWeight", i: int) -> bool:
        """Check if (Λ + ρ̂, α_i^∨) is an integer."""
        # Get ρ̂
        rho_hat = self._algebra.affine_rho() if hasattr(self._algebra, "affine_rho") else None

        if rho_hat is None:
            return True  # Assume integral if we can't compute

        # Compute pairing
        Lambda_plus_rho = Lambda + rho_hat if hasattr(Lambda, "__add__") else Lambda

        # Get simple coroot
        alpha_vee = self._algebra.simple_coroots().get(i)
        if alpha_vee is None:
            return True

        # Compute scalar product
        try:
            pairing = self._algebra.scalar_product(Lambda_plus_rho, alpha_vee)
            # Check if integer
            if hasattr(pairing, "is_integer"):
                return pairing.is_integer()
            return float(pairing) == int(float(pairing))
        except Exception:
            return True

    def _dot_action(self, w: Any, Lambda: "AffineWeight") -> "AffineWeight":
        """
        Compute the dot action w·Λ = w(Λ + ρ̂) - ρ̂.

        Parameters
        ----------
        w : Weyl group element
            The Weyl group element
        Lambda : AffineWeight
            The weight to act on

        Returns
        -------
        AffineWeight
            The result w·Λ
        """
        from ..core.affine_weight import AffineWeight

        # Get ρ̂
        rho_hat = self._algebra.affine_rho() if hasattr(self._algebra, "affine_rho") else None

        if rho_hat is None:
            # Fallback: just apply w
            if hasattr(Lambda, "weyl_reflect"):
                # Apply simple reflections from reduced word
                result = Lambda
                for i in w.reduced_word():
                    result = result.simple_reflection(i)
                return result
            return Lambda

        # Compute w(Λ + ρ̂) - ρ̂
        Lambda_plus_rho = Lambda + rho_hat

        # Apply w
        if hasattr(Lambda_plus_rho, "weyl_reflect"):
            result = Lambda_plus_rho
            for i in w.reduced_word():
                result = result.simple_reflection(i)
            return result - rho_hat

        return Lambda

    # =========================================================================
    # File I/O for Mathematica Processing
    # =========================================================================

    def save_numerator(
        self,
        weight: "AffineWeight",
        filename: str,
        max_grade: int = 10,
    ) -> None:
        """
        Save numerator to file for Mathematica processing.

        Parameters
        ----------
        weight : AffineWeight
            The highest weight
        filename : str
            Output filename
        max_grade : int
            Maximum grade to compute
        """
        from pathlib import Path

        numerator = self.numerator(weight, max_grade)

        # Create output directory if needed
        filepath = Path(filename)
        filepath.parent.mkdir(parents=True, exist_ok=True)

        # Write coefficients
        with open(filepath, "w") as f:
            f.write(f"# Numerator for weight {weight}\n")
            f.write(f"# Level: {self._level}\n")
            f.write(f"# Max grade: {max_grade}\n")
            f.write("# Format: grade coefficient\n")
            for grade, coeff in sorted(numerator.coefficients.items()):
                f.write(f"{grade} {coeff}\n")

    def save_denominator(self, filename: str, max_grade: int = 10) -> None:
        """
        Save denominator to file for Mathematica processing.

        Parameters
        ----------
        filename : str
            Output filename
        max_grade : int
            Maximum grade to compute
        """
        from pathlib import Path

        from ..core.character import WeylKacDenominator

        denom = WeylKacDenominator(self._algebra)
        inv_denom = denom.inverse(max_grade)

        # Create output directory if needed
        filepath = Path(filename)
        filepath.parent.mkdir(parents=True, exist_ok=True)

        # Write coefficients
        with open(filepath, "w") as f:
            f.write(f"# Inverse denominator for {self._algebra._cartan_type}\n")
            f.write(f"# Max grade: {max_grade}\n")
            f.write("# Format: grade coefficient\n")
            for grade, coeff in sorted(inv_denom.coefficients.items()):
                f.write(f"{grade} {coeff}\n")


# Convenience function
def admissible_character(
    cartan_type: list,
    level_p: int,
    level_u: int,
    weight_labels: Dict[int, int],
    max_grade: int = 10,
) -> "FormalCharacter":
    """
    Convenience function to compute admissible character.

    Parameters
    ----------
    cartan_type : list
        Cartan type, e.g., ['A', 2, 1]
    level_p, level_u : int
        Fractional level parameters: k = -h^∨ + p/u
    weight_labels : dict
        Dynkin labels for the weight
    max_grade : int
        Maximum grade

    Returns
    -------
    FormalCharacter
        The character

    Examples
    --------
    >>> char = admissible_character(
    ...     ['A', 2, 1],
    ...     p=4, u=3,
    ...     weight_labels={0: 0, 1: 1, 2: 0},
    ...     max_grade=5
    ... )
    """
    from ..core.affine_lie_algebra import AffineLieAlgebra
    from ..core.affine_weight import from_dynkin_labels
    from ..fractional.level import FractionalLevel

    algebra = AffineLieAlgebra(cartan_type)
    level = FractionalLevel(cartan_type, p=level_p, u=level_u)
    weight = from_dynkin_labels(algebra, weight_labels)

    kw = KacWakimotoCharacter(algebra, level)
    return kw.character(weight, max_grade)
